spring:
  application:
    name: goalsadvisory
  datasource:
    url: jdbc:mysql://localhost:3306/pbor
    username: root
    password: sai123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: false
  banner:
    location: classpath:banner.txt
  boot:
    admin:
      client:
        enabled: true
        instance:
          prefer-ip: true
        url: http://LTIN698922:8083

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
