spring:
  application:
    name: pbor-service
  datasource:
    url: jdbc:mysql://localhost:3306/pbor
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: always
    serialization:
      write-dates-as-timestamps: false
  banner:
    location: classpath:banner.txt
  boot:
    admin:
      client:
        enabled: true
        instance:
          prefer-ip: true
        url: http://localhost:8083

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
