server:
  port: 8084

spring:
  application:
    name: productcatalog-service

  datasource:
    url: jdbc:mysql://localhost:3306/productcatalog
    username: root
    password: Navahith@2478194
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8083
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always